version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-50-17-203-51.compute-1.amazonaws.com
            port: '5432'
            database: d27ogij0rhd257
            ssl: true
            user: rqrpgpkpjucmqc
            password: aacecd17f38f6ed7e227f607eb260c52dcc8298ef076a49db21e1b33a31b9599
            migrations: true
